version: 1.0.{build}
build_cloud: libcc-20
image: libcc-20-vs2015
build_script:
- ps: >-
    if(($env:APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME -split "/")[0] -eq ($env:APPVEYOR_REPO_NAME -split "/")[0]) {
      Write-warning "Skipping PR build for branch"; Exit-AppveyorBuild
    } else {
      if($env:APPVEYOR_SCHEDULED_BUILD -eq 'True')  {
        script\cibuild.ps1 -buildTests
      } else {
        script\cibuild.ps1
      }
      if ($? -ne 'True') {
        throw "Build failed with exit code $?"
      } else {
        "Build succeeded."
      }
    }
test: off
artifacts:
- path: libchromiumcontent*
  name: libchromiumcontent
